version: '3.8'

services:
  app:
    build: .
    ports:
      - "${APP_PORT}:3000"
    environment:
      - APP_PORT=${APP_PORT}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - OPEN_WEATHER_APP_KEY=${OPEN_WEATHER_APP_KEY}
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 